[package]
name = "no_std_compile"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
libffi = { version = "3.2.0", path = "../../libffi-rs" }
dlmalloc = { version = "0.2.8", features = ["global"] }

[workspace]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"