[package]
name = "call_c_fn_varargs_fn"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
libffi = { version = "3.2.0", path = "../../libffi-rs" }

[build-dependencies]
cc = "1.0"

[lints]
workspace = true
