name: Build & Test
permissions:
  contents: read
  pull-requests: write
on: [push, pull_request]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  macos-latest:
    runs-on: macos-latest
    name: Mac OS
    continue-on-error: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          targets: aarch64-apple-darwin
          components: clippy, rustfmt
      - name: Add additional Rust toolchains
        run: |
          rustup toolchain add 1.85.0-aarch64-apple-darwin
          rustup toolchain add stable-aarch64-apple-darwin
      - name: CI
        run: ./scripts/ci-checks.sh

  ubuntu-latest:
    name: Ubuntu
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          targets: x86_64-unknown-linux-gnu
          components: clippy, rustfmt
      - name: Add additional Rust toolchains
        run: |
          rustup toolchain add 1.85.0-x86_64-unknown-linux-gnu
          rustup toolchain add stable-x86_64-unknown-linux-gnu
      - name: CI
        run: ./scripts/ci-checks.sh
      - name: CI for other CPU archs
        run: ./scripts/targettest.sh SETUP

  windows-latest-gnu:
    runs-on: windows-latest
    name: Windows GNU
    continue-on-error: true
    steps:
      - uses: msys2/setup-msys2@61f9e5e925871ba6c9e3e8da24ede83ea27fa91f # v2.27.0
        with:
          release: false
          path-type: inherit
          msystem: UCRT64
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-gnu
          components: clippy, rustfmt
      - name: Add additional Rust toolchains
        run: |
          rustup toolchain add 1.85.0-x86_64-pc-windows-gnu
          rustup toolchain add stable-x86_64-pc-windows-gnu
      - name: CI
        run: .\scripts\ci-checks.bat

  windows-latest-msvc:
    strategy:
      fail-fast: false
      matrix:
        target:
        - x86_64-pc-windows-msvc
        - i686-pc-windows-msvc
    name: Windows MSVC - ${{ matrix.target }}
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}
          components: clippy, rustfmt
      - name: Add additional Rust toolchains
        run: |
          rustup toolchain add 1.85.0-${{ matrix.target }}
          rustup toolchain add stable-${{ matrix.target }}
      - name: CI
        run: .\scripts\ci-checks.bat
