name: Build & Test
permissions:
  contents: read
  pull-requests: write
on: [push, pull_request]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  macos-latest:
    runs-on: macos-latest
    name: Mac OS
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          targets: aarch64-apple-darwin
          components: clippy, rustfmt, miri
      - name: Add additional Rust toolchains
        run: |
          rustup toolchain install 1.85.0
          rustup toolchain install stable
      - name: CI
        run: ./scripts/ci-checks.sh

  ubuntu-latest:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          targets: x86_64-unknown-linux-gnu
          components: clippy, rustfmt, miri
      - name: Add additional Rust toolchains
        run: |
          rustup toolchain install 1.85.0
          rustup toolchain install stable
      - name: CI
        run: ./scripts/ci-checks.sh
      - name: CI for other CPU archs
        run: ./scripts/targettest.sh SETUP

  windows-latest-gnu:
    runs-on: windows-latest
    name: Windows GNU
    steps:
      - uses: msys2/setup-msys2@61f9e5e925871ba6c9e3e8da24ede83ea27fa91f # v2.27.0
        with:
          release: false
          path-type: inherit
          msystem: UCRT64
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly-x86_64-pc-windows-gnu
          targets: x86_64-pc-windows-gnu
          components: clippy, rustfmt, miri
      - name: Add additional Rust toolchains
        run: |
          rustup toolchain install --target x86_64-pc-windows-gnu 1.85.0-x86_64-pc-windows-gnu
          rustup toolchain install --target x86_64-pc-windows-gnu stable-x86_64-pc-windows-gnu
      - name: CI
        # I was unable to get *-gnu to play nice with scripts/ci-checks.bat, so this action will
        # only execute part of the script instead.
        shell: msys2 {0}
        run: |
          cargo +nightly-x86_64-pc-windows-gnu fmt --all --check --verbose
          cargo +nightly-x86_64-pc-windows-gnu fmt --manifest-path=examples/no_std_run/Cargo.toml --all --check --verbose
          cargo +nightly-x86_64-pc-windows-gnu clippy --all --all-targets --all-features --verbose -- -D warnings
          cargo +nightly-x86_64-pc-windows-gnu clippy --manifest-path=examples/no_std_run/Cargo.toml --all --all-features --verbose -- -D warnings
          cargo +1.85.0-x86_64-pc-windows-gnu test --workspace --all-targets --verbose
          cargo +stable-x86_64-pc-windows-gnu test --workspace --all-targets --verbose
          cargo +nightly-x86_64-pc-windows-gnu test --workspace --all-targets --verbose
          cargo +nightly-x86_64-pc-windows-gnu miri test --workspace --lib --verbose
          cargo +1.85.0-x86_64-pc-windows-gnu run --example call_c_fn --verbose
          cargo +stable-x86_64-pc-windows-gnu run --example call_c_fn --verbose
          cargo +nightly-x86_64-pc-windows-gnu run --example call_c_fn --verbose
          cargo +1.85.0-x86_64-pc-windows-gnu run --manifest-path=examples/no_std_run/Cargo.toml --verbose
          cargo +stable-x86_64-pc-windows-gnu run --manifest-path=examples/no_std_run/Cargo.toml --verbose
          cargo +nightly-x86_64-pc-windows-gnu run --manifest-path=examples/no_std_run/Cargo.toml --verbose

  windows-latest-msvc:
    strategy:
      fail-fast: false
      matrix:
        target:
        - x86_64-pc-windows-msvc
        - i686-pc-windows-msvc
    name: Windows MSVC - ${{ matrix.target }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # 2025-03-15
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}
          components: clippy, rustfmt, miri
      - name: Add additional Rust toolchains
        run: |
          rustup toolchain install 1.85.0
          rustup toolchain install stable
      - name: CI
        run: .\scripts\ci-checks.bat
